### ISSUE TITLE
URL passed as argument in hbs preview-template is converted to a link by autolink plugin

### ISSUE THREAD

**Issue by NullVoxPopuli** [josemarluedke/remark-hbs#14]
idk if there is anything to do about this, but it seems there is maybe an ordering issue? idk, or the auto linker needs to escape arguments?

example:

```md
\`\`\`hbs preview-template
<MyLink @href="https://docfy.dev">
  some text
</MyLink>
\`\`\`
```

**Comment by josemarluedke** [comment]
This issue seems to be something similar to #13. This plugin doesn't have any special treatment for preview-template.

In Docfy, this seems to work correctly: 

![image](https://user-images.githubusercontent.com/230476/109598008-3ae67c00-7acd-11eb-8a6a-deddacec2a46.png)

**Comment by NullVoxPopuli** [comment]
It this test, did you have auto linking?

**Comment by josemarluedke** [comment]
Yep: 

![image](https://user-images.githubusercontent.com/230476/109599673-6dde3f00-7ad0-11eb-952e-a6cb1c67ccf9.png)

**Comment by NullVoxPopuli** [comment]
Huh, for me, I had an a tag inserted into my arg. I'll debug a bit tomorrow and see if I can find more details

**Comment by josemarluedke** [comment]
@NullVoxPopuli Do you still have this problem? Can we close it?

**Comment by NullVoxPopuli** [comment]
yeah, I haven't come across anything similar in a while
