### ISSUE TITLE
remark@next (13)

### ISSUE THREAD

**Issue by wooorm** [josemarluedke/remark-hbs#5]
Hi!

remark is switching to a new parser internally ([micromark](https://github.com/micromark/micromark), [`remarkjs/remark#536`](https://github.com/remarkjs/remark/pull/536)).
It seems this plugin should be fine, however, it would be good to check that in the future (there is `13.0.0-alpha.0` published now, and one or two more will come before the release)

**Comment by josemarluedke** [comment]
Thank you. This plugin is now upgraded and should work just fine under the new release.
